using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace secl
{
    public sealed class AutoCompleteMenuCreator
    {
        /// <summary>
        /// Recreate the auto complete menu.
        /// </summary>
        /// <param name="editor"></param>
        /// <returns></returns>
        public static void CreateMenu(SharpControl editor)
        {
            AutocompleteMenu Menu = new AutocompleteMenu(editor);
            Menu.SearchPattern = @"[\w\.:=!<>]";
            Menu.AllowTabKey = true;

            var items = new string[]
            {
                "<html>",
                "<head>",
                "<title>",
                "<body>",
                "<DOCTYPE>",
                "<fieldset>",
                "<table>",
                "<tr>",
                "<th>",
                "<tb>",
                "<tbody>",
                "<center>",
                "<div>",
                "<footer>",
                "<input>",
                "<textarea>",
                "<iframe>",
                "<script>",
                "<form>",
                "<!-- -->",
                "<address",
                "<abbr>",
                "<area>",
                "<article>",
                "<aside>",
                "<audio>",
                "<video>",
                "<b>",
                "<bdi>",
                "<bdo>",
                "<blockquote>",
                "<br>",
                "<button>",
                "<canvas>",
                "<caption>",
                "<cite>",
                "<code>",
                "<col>",
                "<colgroup>",
                "<datalist>",
                "<dd>",
                "<del>",
                "<details>",
                "<dfn>",
                "<dialog>",
                "<dl>",
                "<em>",
                "<embed>",
                "<figure>",
                "<footer>",
                "<h1>",
                "<h2>",
                "<h3>",
                "<h4>",
                "<h5>",
                "<h6>",
                "<header>",
                "<hr>",
                "<img>",
                "<ins>",
                "<kbd>",
                "<keygen>",
                "<label>",
                "<legand>",
                "<li>",
                "<link>",
                "<main>",
                "<map>",
                "<mark>",
                "<menu>",
                "<menuitem>",
                "<meta>",
                "<meter>",
                "<nav>",
                "<noscript>",
                "<object>",
                "<ol>",
                "<optgroup>",
                "<option>",
                "<output>",
                "<p>",
                "<param>",
                "<pre>",
                "<progress>",
                "<q>",
                "<rp>",
                "<rt>",
                "<ruby>",
                "<s>",
                "<samp>",
                "<section>",
                "<select>",
                "<source>",
                "<span>",
                "<strong>",
                "<style>",
                "<summary>",
                "<sup>",
                "<table>",
                "<tfoot>",
                "<track>",
                "<u>",
                "<ul>",
                "<var>",
                "<wbr>",
                "function",
                "window",
                "var",
                "document",
                "padding",
                "margin",
                "font-family",
                "font-size",
                "font-weight",
                "font-style",
                "border",
                "border-left",
                "border-right",
                "border-top",
                "border-bottom",
                "left",
                "right",
                "top",
                "bottom",
                "margin-top",
                "margin-bottom",
                "margin-right",
                "margin-left",
                "margin",
                "padding-top",
                "padding-bottom",
                "padding-left",
                "padding-right",
                "padding",
                "z-index",
                "width",
                "height",
                "display",
                "background",
                "box-shadow",
                "float",
                "color",
                "background-color",
                "background-image",
                "background-attachment",
                "background-blend-mode",
                "background-position",
                "background-repeat",
                "background-clip",
                "background-size",
                "border-radius",
                "border-button-left-radius",
                "border-button-right-radius",
                "border-color",
                "border-image",
                "border-image-outset",
                "border-image-repeat",
                "border-image-source",
                "border-image-width",
                "border-left-color",
                "border-left-style",
                "border-left-white",
                "border-right-color",
                "border-right-style",
                "border-right-white",
                "border-style",
                "border-top-color",
                "border-top-style",
                "border-top-white",
                "border-bottom-color",
                "border-bottom-style",
                "border-bottom-white",
                "text-align",
                "text-decoration",
                "transition",
                "-moz-transition",
                "webkit-transition",
                "-moz-box-shadow",
                "-webkit-box-shadow"
            };
            List<string> items0 = new List<string>();
            items0.AddRange(items);
            Menu.Items.Font = new System.Drawing.Font("Open Sans", 8);
            Menu.Items.SetAutocompleteItems(items0);
            editor.AutoMenu = Menu;
        }
    }
}
